version: "3.9"

services:
  backend:
    build: ./backend
    container_name: car_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    networks:
      - car_network

  frontend:
    build: ./frontend
    container_name: car_frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    environment:
      VITE_API_URL: "http://localhost:8000"   # Frontend points to backend
    networks:
      - car_network

networks:
  car_network: